Refactor popup event handling for onOpen and onClose
When using maplibre-gl, adding a Popup component causes the error "Uncaught TypeError: (new window.MapLib.Popup(...)).on(...).on is not a function". This PR fixes that.